<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\ItemRepresentation $item
 * @var \Omeka\Api\Representation\ItemRepresentation[] $data
 * @var string $type
 * @var array $options
 */

$translate = $this->plugin('translate');

if (empty($data) && !empty($options['hideIfEmpty'])):
    return;
endif;

if (isset($options['title'])):
    $title = $options['title'];
else:
    $title = [
        'tree' => $translate('Tree of concepts'),
        'branch' => $translate('Branch of current concept'),
        'custom' => $translate('Tree of concepts'),
    ];
    $title = $title[$type];
endif;
?>

<div class="thesaurus thesaurus-tree <?= $options['class'] ?>">
    <h4><?= $title ?></h4>
    <?php if (empty($data)): ?>
    <p>
        <?= $translate('No concept.') ?>
    </p>
    <?php else: ?>
        <?= $this->partial('common/thesaurus-tree-recursive', ['data' => $data, 'options' => $options]); ?>
    <?php endif; ?>
</div>
