<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\ItemRepresentation $item
 * @var \Omeka\Api\Representation\ItemRepresentation[] $data
 * @var string $type
 * @var array $options
 */

$translate = $this->plugin('translate');

if (empty($data) && !empty($options['hideIfEmpty'])):
    return;
endif;

if (isset($options['title'])):
    $title = $options['title'];
else:
    $title = [
        'tops' => $translate('Top concepts'),
        'narrowers' => $translate('Narrower concepts'),
        'relateds' => $translate('Related concepts'),
        'siblings' => $translate('Sibling concepts'),
        // The title is the same than siblings.
        'siblingsOrSelf' => $translate('Sibling concepts'),
        'ascendants' => $translate('Ascendant concepts'),
        'descendants' => $translate('Descendant concepts'),
        'custom' => $translate('Linked concepts'),
    ];
    $title = $title[$type];
endif;

$itemId = $item ? $item->id() : null;
$linkTerm = $this->linkTerm($options);
?>

<div class="thesaurus thesaurus-list <?= $options['class'] ?>">
    <h4><?= $title ?></h4>
    <?php if (empty($data)): ?>
    <p>
        <?= $translate('No concept.') ?>
    </p>
    <?php else: ?>
    <ul>
        <?php foreach ($data as $concept): ?>
        <?php $isItem = (is_object($concept) ? $concept->id() : $concept['id']) === $itemId; ?>
        <li<?php if ($isItem) echo ' class="active"'; ?>><?= $linkTerm->render($concept) ?></li>
        <?php endforeach; ?>
    </ul>
    <?php endif; ?>
</div>
