<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\ItemRepresentation $item
 * @var \Omeka\Api\Representation\ItemRepresentation[] $data
 * @var string $type
 * @var array $options
 */

$plugins = $this->getHelperPluginManager();
$translate = $this->plugin('translate');
$escape = $plugins->get('escapeHtml');

if (empty($data) && !empty($options['hideIfEmpty'])):
    return;
endif;

if (isset($options['title'])):
    $title = $options['title'];
else:
    $title = [
        'tops' => 'Top concepts', // @translate
        'narrowers' => 'Narrower concepts', // @translate
        'narrowersOrSelf' => 'Narrower concepts', // @translate
        'relateds' => 'Related concepts', // @translate
        'relatedsOrSelf' => 'Related concepts', // @translate
        'siblings' => 'Sibling concepts', // @translate
        'siblingsOrSelf' => 'Sibling concepts', // @translate
        'ascendants' => 'Ascendant concepts', // @translate
        'ascendantsOrSelf' => 'Ascendant concepts', // @translate
        'descendants' => 'Descendant concepts', // @translate
        'descendantsOrSelf' => 'Descendant concepts', // @translate
        'custom' => 'Linked concepts', // @translate
    ];
    $title = isset($title[$type]) ? $translate($title[$type]) : '';
endif;

$itemId = $item ? $item->id() : null;
$linkTerm = $this->linkTerm($options);
?>

<div class="thesaurus thesaurus-list <?= $options['class'] ?>">
    <h4><?= $escape($title) ?></h4>
    <?php if (empty($data)): ?>
    <p>
        <?= $translate('No concept.') ?>
    </p>
    <?php else: ?>
    <ul>
        <?php foreach ($data as $concept): ?>
        <?php $isCurrent = (is_object($concept) ? $concept->id() : $concept['id']) === $itemId; ?>
        <li<?php if ($isCurrent) echo ' class="active"'; ?>><?= $linkTerm->render($concept) ?></li>
        <?php endforeach; ?>
    </ul>
    <?php endif; ?>
</div>
