<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\ItemRepresentation $item
 * @var \Omeka\Api\Representation\ItemRepresentation[] $data
 * @var string $type
 * @var array $options
 */

$translate = $this->plugin('translate');

if (empty($data) && !empty($options['hideIfEmpty'])):
    return;
endif;

if (empty($options['title'])):
    $title = [
        'tree' => $translate('Tree of concepts'),
        'branch' => $translate('Branch of current concept'),
    ];
    $title = $title[$type];
else:
    $title = $options['title'];
endif;

?>
<div class="thesaurus thesaurus-tree">
    <h4><?= $title ?></h4>
    <?php if (empty($data)): ?>
    <p>
        <?= $translate('No concept.') ?>
    </p>
    <?php else: ?>
    <?php // This process doesn't use a recursive function, but supposes that the depth is < 10. ?>
    <?php // TODO Add an option for depth of the tree. ?>
    <ul>
        <?php foreach ($data as $concept_1): ?>
        <li><?= $concept_1['current']->linkPretty() ?>
        <?php if (!empty($concept_1['narrowers'])): ?>
            <ul>
            <?php foreach ($concept_1['narrowers'] as $concept_2): ?>
                <li><?= $concept_2['current']->linkPretty() ?>
                <?php if (!empty($concept_2['narrowers'])): ?>
                    <ul>
                    <?php foreach ($concept_2['narrowers'] as $concept_3): ?>
                        <li><?= $concept_3['current']->linkPretty() ?>
                        <?php if (!empty($concept_3['narrowers'])): ?>
                            <ul>
                            <?php foreach ($concept_3['narrowers'] as $concept_4): ?>
                                <li><?= $concept_4['current']->linkPretty() ?>
                                <?php if (!empty($concept_4['narrowers'])): ?>
                                    <ul>
                                    <?php foreach ($concept_4['narrowers'] as $concept_5): ?>
                                        <li><?= $concept_5['current']->linkPretty() ?>
                                        <?php if (!empty($concept_5['narrowers'])): ?>
                                            <ul>
                                            <?php foreach ($concept_5['narrowers'] as $concept_6): ?>
                                                <li><?= $concept_6['current']->linkPretty() ?>
                                                <?php if (!empty($concept_6['narrowers'])): ?>
                                                    <ul>
                                                    <?php foreach ($concept_6['narrowers'] as $concept_7): ?>
                                                        <li><?= $concept_7['current']->linkPretty() ?>
                                                        <?php if (!empty($concept_7['narrowers'])): ?>
                                                            <ul>
                                                            <?php foreach ($concept_7['narrowers'] as $concept_8): ?>
                                                                <li><?= $concept_8['current']->linkPretty() ?>
                                                                <?php if (!empty($concept_8['narrowers'])): ?>
                                                                    <ul>
                                                                    <?php foreach ($concept_8['narrowers'] as $concept_9): ?>
                                                                        <li><?= $concept_9['current']->linkPretty() ?>
                                                                    <?php endforeach; ?>
                                                                   </ul>
                                                               <?php endif; ?>
                                                               </li>
                                                            <?php endforeach; ?>
                                                           </ul>
                                                       <?php endif; ?>
                                                       </li>
                                                    <?php endforeach; ?>
                                                   </ul>
                                               <?php endif; ?>
                                               </li>
                                            <?php endforeach; ?>
                                           </ul>
                                       <?php endif; ?>
                                       </li>
                                    <?php endforeach; ?>
                                   </ul>
                                   <?php endif; ?>
                               </li>
                               <?php endforeach; ?>
                            </ul>
                            <?php endif; ?>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                    <?php endif; ?>
                </li>
                <?php endforeach; ?>
            </ul>
            <?php endif; ?>
        </li>
        <?php endforeach; ?>
    </ul>
    <?php endif; ?>
</div>
