<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\ItemRepresentation $item
 * @var array $data
 * @var string $type
 * @var array $options
 */

if (empty($data) && !empty($options['hideIfEmpty'])):
    return;
endif;

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escape = $plugins->get('escapeHtml');
$partial = $plugins->get('partial');

if (isset($options['title'])):
    $title = $options['title'];
else:
    $title = [
        'tree' => 'Tree of concepts', // @translate
        'branch' => 'Branch of current concept', // @translate
        'branchNoTop' => 'Branch of current concept', // @translate
        'branchFromItem' => 'Tree of current concept', // @translate
        'branchBelowItem' => 'Descendants of current concept', // @translate
        'custom' => 'Tree of concepts', // @translate
    ];
    $title = isset($title[$type]) ? $translate($title[$type]) : '';
endif;

$linkTerm = $this->linkTerm($options);
?>

<div class="thesaurus thesaurus-tree <?= $options['class'] ?>">
    <h4><?= $escape($title) ?></h4>
    <?php if (!count($data)): ?>
    <p>
        <?= $translate('No concept.') ?>
    </p>
    <?php else: ?>
        <?= $partial('common/thesaurus-tree-recursive', [
            'itemId' => $item->id(),
            'data' => $data,
            'options' => $options,
            'linkTerm' => $linkTerm,
            'partial' => $partial,
            'level' => 0,
        ]) ?>
    <?php endif; ?>
</div>
