<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\ItemRepresentation $item
 * @var \Omeka\Api\Representation\ItemRepresentation $data
 * @var string $type
 * @var array $options
 */

if (empty($data) && !empty($options['hideIfEmpty'])):
    return;
endif;

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');

if (isset($options['title'])):
    $title = $options['title'];
else:
    $title = [
        'root' => 'Root concept', // @translate
        'broader' => 'Broader concept', // @translate
        'custom' => 'Specific concept', // @translate
    ];
    $title = isset($title[$type]) ? $translate($title[$type]) : '';
endif;

$linkTerm = $this->linkTerm($options);
?>

<div class="thesaurus thesaurus-single <?= $options['class'] ?>">
    <h4><?= $escape($title) ?></h4>
    <?php if (empty($data)): ?>
    <p>
        <?= $translate('No concept.') ?>
    </p>
    <?php else: ?>
    <p>
        <?= $linkTerm->render($data) ?>
    </p>
    <?php endif; ?>
</div>
