<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $data
 * @var array $options
 * @var \Thesaurus\View\Helper\LinkTerm $linkTerm
 * @var int $level
 */

?>
<ul>
    <?php foreach ($data as $current): ?>
    <li><?= $linkTerm->render($current['self']) ?>
        <?php if (!empty($current['children'])): ?>
        <?= $this->partial('common/thesaurus-tree-recursive', ['data' => $current['children'], 'options' => $options, 'linkTerm' => $linkTerm, 'level' => $level + 1]) ?>
        <?php endif; ?>
   </li>
   <?php endforeach; ?>
</ul>
