<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var string $heading
 * @var string $params
 */

$escape = $this->plugin('escapeHtml');

$params = parse_ini_string($params);
$item = empty($params['item'])
    ? null
    : $this->api()->searchOne('items', ['id' => $params['item']])->getContent();
$type = empty($params['type']) ? 'tree' : $params['type'];

?>

<div class="block-simple">
    <?php if ($heading): ?>
    <h2><?= $escape($heading) ?></h2>
    <?php endif; ?>
    <?php if ($item): ?>
    <?= $this->thesaurus($item)->display($type, ['title' => '']) ?>
    <?php endif; ?>
</div>
