<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var string $heading
 * @var \Omeka\Api\Representation\ItemRepresentation $item
 * @var string $type
 * @var array $options
 */

?>

<div class="block-thesaurus">
    <?php if ($heading): ?>
    <h2><?= $this->escapeHtml($heading) ?></h2>
    <?php endif; ?>
    <?php if ($item): ?>
    <?= $this->thesaurus($item)->display($type, $options) ?>
    <?php endif; ?>
</div>
