<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Thesaurus\Form\ConvertForm $form
 */

$translate = $this->plugin('translate');

$this->headLink()
    ->appendStylesheet($assetUrl('css/thesaurus-admin.css', 'Thesaurus'));

$this->htmlElement('body')->appendAttribute('class', 'thesaurus tree convert');

$form->prepare();
?>

<?= $this->pageTitle($translate('Convert'), 1, $translate('Thesaurus')) ?>

<p class="explanation">
    <?= $translate('Convert a flat list into a flat thesaurus.') ?>
</p>
<p>
    <?= $this->form()->openTag($form) ?>
    <?= $this->formCollection($form, false) ?>
    <?= $this->form()->closeTag($form) ?>
</p>
