<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Thesaurus\Form\ConvertForm $form
 */

$translate = $this->plugin('translate');
$form->prepare();
?>

<?= $this->pageTitle($translate('Thesaurus convert')) ?>
<h3><?= $translate('Convert') ?></h3>
<p class="explanation">
    <?= $translate('Convert a flat list into a flat thesaurus.') ?>
</p>
<p>
    <?= $this->form()->openTag($form) ?>
    <?= $this->formCollection($form, false) ?>
    <?= $this->form()->closeTag($form) ?>
</p>
