<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Form\ResourceForm $form
 * @var \Omeka\Api\Representation\ItemRepresentation $item
 * @var \Omeka\Api\Representation\ItemRepresentation $resource
 * @var array $mediaForms
 * @var string $submitLabel
 * @var string $deleteButton
 * @var string $sectionNavEvent
 * @var string $action
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escape = $plugins->get('escapeHtml');
$formElement = $plugins->get('formElement');
$assetUrl = $plugins->get('assetUrl');

$this->headLink()
    ->appendStylesheet($assetUrl('css/thesaurus-admin.css', 'Thesaurus'));
$this->headScript()
    ->appendFile($assetUrl('vendor/sortablejs/Sortable.min.js', 'Omeka'))
    ->appendFile($assetUrl('js/resource-form.js', 'Omeka'));
$form->prepare();
?>

<?= $this->form()->openTag($form); ?>

<?= $this->sectionNav([
    'resource-values' => $translate('Concept scheme'),
    // TODO Créer un onglet spécifique pour le contenu du thésaurus (concept-scheme/concept) ?
    // 'thesaurus' => $translate('Thesaurus'),
    'item-media' => $translate('Media'),
    'item-sets' => $translate('Item sets'),
    'sites' => $translate('Sites'),
    'advanced-settings' => $translate('Advanced'),
], $sectionNavEvent) ?>

<?php $this->trigger("view.$action.form.before", ['form' => $form]); ?>

<?php // Simpler than modify form with "input hidden". ?>
<?= $this->partial('thesaurus/admin/thesaurus/resource-fields-thesaurus.phtml', [
    'form' => $form,
    'resource' => $item,
    'action' => $action,
]) ?>

<fieldset id="item-media" class="section" aria-labelledby="media-label">
    <?= $this->partial('omeka/admin/item/manage-media', [
        'mediaForms' => $mediaForms,
        'resource' => $item,
    ]) ?>
</fieldset>

<fieldset id="item-sets" class="section" aria-labelledby="item-sets-label">
    <?= $this->partial('omeka/admin/item/manage-item-sets', [
        'item' => $item,
    ]) ?>
</fieldset>

<fieldset id="sites" class="section" aria-labelledby="sites-label">
    <?= $this->partial('omeka/admin/item/manage-sites', [
        'item' => $item,
    ]) ?>
</fieldset>

<div id="page-actions">
    <?php if ($item && $item->isPublic() || (!isset($item)) && !$this->setting('default_to_private')) : ?>
    <?= $this->hyperlink('', '#', [
        'class' => 'o-icon-public button',
        'title' => $translate('Make private'),
    ]) ?>
    <input type="hidden" name="o:is_public" value="1">
    <?php else: ?>
    <?= $this->hyperlink('', '#', [
        'class' => 'o-icon-private button',
        'title' => $translate('Make public'),
    ]) ?>
    <input type="hidden" name="o:is_public" value="0">
    <?php endif; ?>
    <?= (isset($deleteButton)) ? $deleteButton : '' ?>
    <?= $this->cancelButton() ?>
    <button type="submit" name="add-item-submit"><?= $escape($submitLabel) ?></button>
</div>

<?php $this->trigger("view.$action.form.after", ['form' => $form]); ?>

<?= $formElement($form->get('csrf')) ?>

<?= $this->form()->closeTag() ?>

<?= $this->partial('common/resource-form-templates.phtml') ?>
