<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\ItemRepresentation $item
 * @var \Omeka\Api\Representation\ItemRepresentation $resource
 * @var \Laminas\Form\Form $form
 */

// The thesaurus is loaded dynamically via js. Else it is possible to use $this->thesaurus($item)->display().

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$isAllowed = $item->userIsAllowed('batch-edit');
if ($isAllowed && $form): $form->prepare(); else: $form = null; endif;

$this->headLink()
    ->prependStylesheet($assetUrl('css/advanced-search.css', 'Omeka'))
    ->appendStylesheet($assetUrl('css/jstree.css', 'Omeka'))
    ->appendStylesheet($assetUrl('css/query-form.css', 'Omeka'))
    ->appendStylesheet($assetUrl('css/thesaurus-admin.css', 'Thesaurus'));
$this->headScript()
    ->appendFile($assetUrl('vendor/jstree/jstree.min.js', 'Omeka'))
    ->appendFile($assetUrl('js/jstree-plugins.js', 'Omeka'))
    ->appendFile($assetUrl('js/query-form.js', 'Omeka'))
    ->appendFile($assetUrl('js/advanced-search.js', 'Omeka'), 'text/javascript', ['async' => 'async', 'defer' => 'defer'])
    ->appendFile($assetUrl('js/thesaurus-admin.js', 'Thesaurus'), 'text/javascript', ['async' => 'async', 'defer' => 'defer'])
;
$this->htmlElement('body')->appendAttribute('class', 'thesaurus tree');
?>

<?= $this->pageTitle($item->displayTitle(), 1, $translate('Thesaurus')) ?>

<?php if ($form): ?>
<?= $this->form()->openTag($form) ?>
<?= $this->formRow($form->get('form_csrf')) ?>

<div id="page-actions">
    <?= $this->cancelButton() ?>
    <button type="submit"><?= $translate('Save') ?></button>
</div>
<?php endif; ?>

<div id="jstree"
    data-link-form-url="<?= $form ? $escapeAttr($url('admin/thesaurus/id', ['action' => 'tree'], true)) : '' ?>"
    data-jstree-url="<?= $escapeAttr($url('admin/thesaurus/id', ['action' => 'jstree'], true)) ?>">
</div>

<?php if ($form): ?>
<?= $this->form()->closeTag() ?>
<?php endif; ?>
